// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphqlService.proto

package com.personal.models;

public interface BankOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Bank)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string common_name = 2;</code>
   */
  java.lang.String getCommonName();
  /**
   * <code>string common_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getCommonNameBytes();
}
