// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphqlService.proto

package com.personal.models;

public interface GraphQLRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GraphQLRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
