// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphqlService.proto

package com.personal.models;

public interface GraphQLResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GraphQLResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.QueryType data = 1;</code>
   */
  boolean hasData();
  /**
   * <code>.QueryType data = 1;</code>
   */
  com.personal.models.QueryType getData();
  /**
   * <code>.QueryType data = 1;</code>
   */
  com.personal.models.QueryTypeOrBuilder getDataOrBuilder();
}
