// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphqlService.proto

package com.personal.models;

/**
 * Protobuf type {@code QueryType}
 */
public  final class QueryType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:QueryType)
    QueryTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryType.newBuilder() to construct.
  private QueryType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryType() {
    getWiringInstructions_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private QueryType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.personal.models.WiringInstruction.Builder subBuilder = null;
            if (getWiringInstruction_ != null) {
              subBuilder = getWiringInstruction_.toBuilder();
            }
            getWiringInstruction_ = input.readMessage(com.personal.models.WiringInstruction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(getWiringInstruction_);
              getWiringInstruction_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              getWiringInstructions_ = new java.util.ArrayList<com.personal.models.WiringInstruction>();
              mutable_bitField0_ |= 0x00000002;
            }
            getWiringInstructions_.add(
                input.readMessage(com.personal.models.WiringInstruction.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        getWiringInstructions_ = java.util.Collections.unmodifiableList(getWiringInstructions_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.personal.models.GraphQLServiceProto.internal_static_QueryType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.personal.models.GraphQLServiceProto.internal_static_QueryType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.personal.models.QueryType.class, com.personal.models.QueryType.Builder.class);
  }

  private int bitField0_;
  public static final int GET_WIRING_INSTRUCTION_FIELD_NUMBER = 1;
  private com.personal.models.WiringInstruction getWiringInstruction_;
  /**
   * <code>.WiringInstruction get_wiring_instruction = 1;</code>
   */
  public boolean hasGetWiringInstruction() {
    return getWiringInstruction_ != null;
  }
  /**
   * <code>.WiringInstruction get_wiring_instruction = 1;</code>
   */
  public com.personal.models.WiringInstruction getGetWiringInstruction() {
    return getWiringInstruction_ == null ? com.personal.models.WiringInstruction.getDefaultInstance() : getWiringInstruction_;
  }
  /**
   * <code>.WiringInstruction get_wiring_instruction = 1;</code>
   */
  public com.personal.models.WiringInstructionOrBuilder getGetWiringInstructionOrBuilder() {
    return getGetWiringInstruction();
  }

  public static final int GET_WIRING_INSTRUCTIONS_FIELD_NUMBER = 2;
  private java.util.List<com.personal.models.WiringInstruction> getWiringInstructions_;
  /**
   * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
   */
  public java.util.List<com.personal.models.WiringInstruction> getGetWiringInstructionsList() {
    return getWiringInstructions_;
  }
  /**
   * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
   */
  public java.util.List<? extends com.personal.models.WiringInstructionOrBuilder> 
      getGetWiringInstructionsOrBuilderList() {
    return getWiringInstructions_;
  }
  /**
   * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
   */
  public int getGetWiringInstructionsCount() {
    return getWiringInstructions_.size();
  }
  /**
   * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
   */
  public com.personal.models.WiringInstruction getGetWiringInstructions(int index) {
    return getWiringInstructions_.get(index);
  }
  /**
   * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
   */
  public com.personal.models.WiringInstructionOrBuilder getGetWiringInstructionsOrBuilder(
      int index) {
    return getWiringInstructions_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (getWiringInstruction_ != null) {
      output.writeMessage(1, getGetWiringInstruction());
    }
    for (int i = 0; i < getWiringInstructions_.size(); i++) {
      output.writeMessage(2, getWiringInstructions_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (getWiringInstruction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGetWiringInstruction());
    }
    for (int i = 0; i < getWiringInstructions_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getWiringInstructions_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.personal.models.QueryType)) {
      return super.equals(obj);
    }
    com.personal.models.QueryType other = (com.personal.models.QueryType) obj;

    boolean result = true;
    result = result && (hasGetWiringInstruction() == other.hasGetWiringInstruction());
    if (hasGetWiringInstruction()) {
      result = result && getGetWiringInstruction()
          .equals(other.getGetWiringInstruction());
    }
    result = result && getGetWiringInstructionsList()
        .equals(other.getGetWiringInstructionsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGetWiringInstruction()) {
      hash = (37 * hash) + GET_WIRING_INSTRUCTION_FIELD_NUMBER;
      hash = (53 * hash) + getGetWiringInstruction().hashCode();
    }
    if (getGetWiringInstructionsCount() > 0) {
      hash = (37 * hash) + GET_WIRING_INSTRUCTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getGetWiringInstructionsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.personal.models.QueryType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.personal.models.QueryType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.personal.models.QueryType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.personal.models.QueryType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.personal.models.QueryType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.personal.models.QueryType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.personal.models.QueryType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.personal.models.QueryType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.personal.models.QueryType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.personal.models.QueryType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.personal.models.QueryType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.personal.models.QueryType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.personal.models.QueryType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code QueryType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:QueryType)
      com.personal.models.QueryTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.personal.models.GraphQLServiceProto.internal_static_QueryType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.personal.models.GraphQLServiceProto.internal_static_QueryType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.personal.models.QueryType.class, com.personal.models.QueryType.Builder.class);
    }

    // Construct using com.personal.models.QueryType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGetWiringInstructionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (getWiringInstructionBuilder_ == null) {
        getWiringInstruction_ = null;
      } else {
        getWiringInstruction_ = null;
        getWiringInstructionBuilder_ = null;
      }
      if (getWiringInstructionsBuilder_ == null) {
        getWiringInstructions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        getWiringInstructionsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.personal.models.GraphQLServiceProto.internal_static_QueryType_descriptor;
    }

    @java.lang.Override
    public com.personal.models.QueryType getDefaultInstanceForType() {
      return com.personal.models.QueryType.getDefaultInstance();
    }

    @java.lang.Override
    public com.personal.models.QueryType build() {
      com.personal.models.QueryType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.personal.models.QueryType buildPartial() {
      com.personal.models.QueryType result = new com.personal.models.QueryType(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (getWiringInstructionBuilder_ == null) {
        result.getWiringInstruction_ = getWiringInstruction_;
      } else {
        result.getWiringInstruction_ = getWiringInstructionBuilder_.build();
      }
      if (getWiringInstructionsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          getWiringInstructions_ = java.util.Collections.unmodifiableList(getWiringInstructions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.getWiringInstructions_ = getWiringInstructions_;
      } else {
        result.getWiringInstructions_ = getWiringInstructionsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.personal.models.QueryType) {
        return mergeFrom((com.personal.models.QueryType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.personal.models.QueryType other) {
      if (other == com.personal.models.QueryType.getDefaultInstance()) return this;
      if (other.hasGetWiringInstruction()) {
        mergeGetWiringInstruction(other.getGetWiringInstruction());
      }
      if (getWiringInstructionsBuilder_ == null) {
        if (!other.getWiringInstructions_.isEmpty()) {
          if (getWiringInstructions_.isEmpty()) {
            getWiringInstructions_ = other.getWiringInstructions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureGetWiringInstructionsIsMutable();
            getWiringInstructions_.addAll(other.getWiringInstructions_);
          }
          onChanged();
        }
      } else {
        if (!other.getWiringInstructions_.isEmpty()) {
          if (getWiringInstructionsBuilder_.isEmpty()) {
            getWiringInstructionsBuilder_.dispose();
            getWiringInstructionsBuilder_ = null;
            getWiringInstructions_ = other.getWiringInstructions_;
            bitField0_ = (bitField0_ & ~0x00000002);
            getWiringInstructionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGetWiringInstructionsFieldBuilder() : null;
          } else {
            getWiringInstructionsBuilder_.addAllMessages(other.getWiringInstructions_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.personal.models.QueryType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.personal.models.QueryType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.personal.models.WiringInstruction getWiringInstruction_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.personal.models.WiringInstruction, com.personal.models.WiringInstruction.Builder, com.personal.models.WiringInstructionOrBuilder> getWiringInstructionBuilder_;
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    public boolean hasGetWiringInstruction() {
      return getWiringInstructionBuilder_ != null || getWiringInstruction_ != null;
    }
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    public com.personal.models.WiringInstruction getGetWiringInstruction() {
      if (getWiringInstructionBuilder_ == null) {
        return getWiringInstruction_ == null ? com.personal.models.WiringInstruction.getDefaultInstance() : getWiringInstruction_;
      } else {
        return getWiringInstructionBuilder_.getMessage();
      }
    }
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    public Builder setGetWiringInstruction(com.personal.models.WiringInstruction value) {
      if (getWiringInstructionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        getWiringInstruction_ = value;
        onChanged();
      } else {
        getWiringInstructionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    public Builder setGetWiringInstruction(
        com.personal.models.WiringInstruction.Builder builderForValue) {
      if (getWiringInstructionBuilder_ == null) {
        getWiringInstruction_ = builderForValue.build();
        onChanged();
      } else {
        getWiringInstructionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    public Builder mergeGetWiringInstruction(com.personal.models.WiringInstruction value) {
      if (getWiringInstructionBuilder_ == null) {
        if (getWiringInstruction_ != null) {
          getWiringInstruction_ =
            com.personal.models.WiringInstruction.newBuilder(getWiringInstruction_).mergeFrom(value).buildPartial();
        } else {
          getWiringInstruction_ = value;
        }
        onChanged();
      } else {
        getWiringInstructionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    public Builder clearGetWiringInstruction() {
      if (getWiringInstructionBuilder_ == null) {
        getWiringInstruction_ = null;
        onChanged();
      } else {
        getWiringInstruction_ = null;
        getWiringInstructionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    public com.personal.models.WiringInstruction.Builder getGetWiringInstructionBuilder() {
      
      onChanged();
      return getGetWiringInstructionFieldBuilder().getBuilder();
    }
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    public com.personal.models.WiringInstructionOrBuilder getGetWiringInstructionOrBuilder() {
      if (getWiringInstructionBuilder_ != null) {
        return getWiringInstructionBuilder_.getMessageOrBuilder();
      } else {
        return getWiringInstruction_ == null ?
            com.personal.models.WiringInstruction.getDefaultInstance() : getWiringInstruction_;
      }
    }
    /**
     * <code>.WiringInstruction get_wiring_instruction = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.personal.models.WiringInstruction, com.personal.models.WiringInstruction.Builder, com.personal.models.WiringInstructionOrBuilder> 
        getGetWiringInstructionFieldBuilder() {
      if (getWiringInstructionBuilder_ == null) {
        getWiringInstructionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.personal.models.WiringInstruction, com.personal.models.WiringInstruction.Builder, com.personal.models.WiringInstructionOrBuilder>(
                getGetWiringInstruction(),
                getParentForChildren(),
                isClean());
        getWiringInstruction_ = null;
      }
      return getWiringInstructionBuilder_;
    }

    private java.util.List<com.personal.models.WiringInstruction> getWiringInstructions_ =
      java.util.Collections.emptyList();
    private void ensureGetWiringInstructionsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        getWiringInstructions_ = new java.util.ArrayList<com.personal.models.WiringInstruction>(getWiringInstructions_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.personal.models.WiringInstruction, com.personal.models.WiringInstruction.Builder, com.personal.models.WiringInstructionOrBuilder> getWiringInstructionsBuilder_;

    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public java.util.List<com.personal.models.WiringInstruction> getGetWiringInstructionsList() {
      if (getWiringInstructionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(getWiringInstructions_);
      } else {
        return getWiringInstructionsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public int getGetWiringInstructionsCount() {
      if (getWiringInstructionsBuilder_ == null) {
        return getWiringInstructions_.size();
      } else {
        return getWiringInstructionsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public com.personal.models.WiringInstruction getGetWiringInstructions(int index) {
      if (getWiringInstructionsBuilder_ == null) {
        return getWiringInstructions_.get(index);
      } else {
        return getWiringInstructionsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder setGetWiringInstructions(
        int index, com.personal.models.WiringInstruction value) {
      if (getWiringInstructionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGetWiringInstructionsIsMutable();
        getWiringInstructions_.set(index, value);
        onChanged();
      } else {
        getWiringInstructionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder setGetWiringInstructions(
        int index, com.personal.models.WiringInstruction.Builder builderForValue) {
      if (getWiringInstructionsBuilder_ == null) {
        ensureGetWiringInstructionsIsMutable();
        getWiringInstructions_.set(index, builderForValue.build());
        onChanged();
      } else {
        getWiringInstructionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder addGetWiringInstructions(com.personal.models.WiringInstruction value) {
      if (getWiringInstructionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGetWiringInstructionsIsMutable();
        getWiringInstructions_.add(value);
        onChanged();
      } else {
        getWiringInstructionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder addGetWiringInstructions(
        int index, com.personal.models.WiringInstruction value) {
      if (getWiringInstructionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGetWiringInstructionsIsMutable();
        getWiringInstructions_.add(index, value);
        onChanged();
      } else {
        getWiringInstructionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder addGetWiringInstructions(
        com.personal.models.WiringInstruction.Builder builderForValue) {
      if (getWiringInstructionsBuilder_ == null) {
        ensureGetWiringInstructionsIsMutable();
        getWiringInstructions_.add(builderForValue.build());
        onChanged();
      } else {
        getWiringInstructionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder addGetWiringInstructions(
        int index, com.personal.models.WiringInstruction.Builder builderForValue) {
      if (getWiringInstructionsBuilder_ == null) {
        ensureGetWiringInstructionsIsMutable();
        getWiringInstructions_.add(index, builderForValue.build());
        onChanged();
      } else {
        getWiringInstructionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder addAllGetWiringInstructions(
        java.lang.Iterable<? extends com.personal.models.WiringInstruction> values) {
      if (getWiringInstructionsBuilder_ == null) {
        ensureGetWiringInstructionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, getWiringInstructions_);
        onChanged();
      } else {
        getWiringInstructionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder clearGetWiringInstructions() {
      if (getWiringInstructionsBuilder_ == null) {
        getWiringInstructions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        getWiringInstructionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public Builder removeGetWiringInstructions(int index) {
      if (getWiringInstructionsBuilder_ == null) {
        ensureGetWiringInstructionsIsMutable();
        getWiringInstructions_.remove(index);
        onChanged();
      } else {
        getWiringInstructionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public com.personal.models.WiringInstruction.Builder getGetWiringInstructionsBuilder(
        int index) {
      return getGetWiringInstructionsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public com.personal.models.WiringInstructionOrBuilder getGetWiringInstructionsOrBuilder(
        int index) {
      if (getWiringInstructionsBuilder_ == null) {
        return getWiringInstructions_.get(index);  } else {
        return getWiringInstructionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public java.util.List<? extends com.personal.models.WiringInstructionOrBuilder> 
         getGetWiringInstructionsOrBuilderList() {
      if (getWiringInstructionsBuilder_ != null) {
        return getWiringInstructionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(getWiringInstructions_);
      }
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public com.personal.models.WiringInstruction.Builder addGetWiringInstructionsBuilder() {
      return getGetWiringInstructionsFieldBuilder().addBuilder(
          com.personal.models.WiringInstruction.getDefaultInstance());
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public com.personal.models.WiringInstruction.Builder addGetWiringInstructionsBuilder(
        int index) {
      return getGetWiringInstructionsFieldBuilder().addBuilder(
          index, com.personal.models.WiringInstruction.getDefaultInstance());
    }
    /**
     * <code>repeated .WiringInstruction get_wiring_instructions = 2;</code>
     */
    public java.util.List<com.personal.models.WiringInstruction.Builder> 
         getGetWiringInstructionsBuilderList() {
      return getGetWiringInstructionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.personal.models.WiringInstruction, com.personal.models.WiringInstruction.Builder, com.personal.models.WiringInstructionOrBuilder> 
        getGetWiringInstructionsFieldBuilder() {
      if (getWiringInstructionsBuilder_ == null) {
        getWiringInstructionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.personal.models.WiringInstruction, com.personal.models.WiringInstruction.Builder, com.personal.models.WiringInstructionOrBuilder>(
                getWiringInstructions_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        getWiringInstructions_ = null;
      }
      return getWiringInstructionsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:QueryType)
  }

  // @@protoc_insertion_point(class_scope:QueryType)
  private static final com.personal.models.QueryType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.personal.models.QueryType();
  }

  public static com.personal.models.QueryType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryType>
      PARSER = new com.google.protobuf.AbstractParser<QueryType>() {
    @java.lang.Override
    public QueryType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new QueryType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<QueryType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.personal.models.QueryType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

