// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphqlService.proto

package com.personal.models;

/**
 * Protobuf type {@code WiringInstruction}
 */
public  final class WiringInstruction extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WiringInstruction)
    WiringInstructionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WiringInstruction.newBuilder() to construct.
  private WiringInstruction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WiringInstruction() {
    name_ = "";
    bankName_ = "";
    id_ = 0L;
    abaNumber_ = 0L;
    swift_ = "";
    forAccountOf_ = "";
    accountNumber_ = "";
    inFavourOf_ = "";
    inFavourOfAccountNumber_ = "";
    bankId_ = 0L;
    products_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WiringInstruction(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            bankName_ = s;
            break;
          }
          case 24: {

            id_ = input.readInt64();
            break;
          }
          case 32: {

            abaNumber_ = input.readInt64();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            swift_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            forAccountOf_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            accountNumber_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            inFavourOf_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            inFavourOfAccountNumber_ = s;
            break;
          }
          case 80: {

            bankId_ = input.readInt64();
            break;
          }
          case 90: {
            com.personal.models.Bank.Builder subBuilder = null;
            if (bank_ != null) {
              subBuilder = bank_.toBuilder();
            }
            bank_ = input.readMessage(com.personal.models.Bank.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(bank_);
              bank_ = subBuilder.buildPartial();
            }

            break;
          }
          case 98: {
            if (!((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
              products_ = new java.util.ArrayList<com.personal.models.Product>();
              mutable_bitField0_ |= 0x00000800;
            }
            products_.add(
                input.readMessage(com.personal.models.Product.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000800) == 0x00000800)) {
        products_ = java.util.Collections.unmodifiableList(products_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.personal.models.GraphQLServiceProto.internal_static_WiringInstruction_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.personal.models.GraphQLServiceProto.internal_static_WiringInstruction_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.personal.models.WiringInstruction.class, com.personal.models.WiringInstruction.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BANK_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object bankName_;
  /**
   * <code>string bank_name = 2;</code>
   */
  public java.lang.String getBankName() {
    java.lang.Object ref = bankName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bankName_ = s;
      return s;
    }
  }
  /**
   * <code>string bank_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBankNameBytes() {
    java.lang.Object ref = bankName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bankName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 3;
  private long id_;
  /**
   * <code>int64 id = 3;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int ABA_NUMBER_FIELD_NUMBER = 4;
  private long abaNumber_;
  /**
   * <code>int64 aba_number = 4;</code>
   */
  public long getAbaNumber() {
    return abaNumber_;
  }

  public static final int SWIFT_FIELD_NUMBER = 5;
  private volatile java.lang.Object swift_;
  /**
   * <code>string swift = 5;</code>
   */
  public java.lang.String getSwift() {
    java.lang.Object ref = swift_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      swift_ = s;
      return s;
    }
  }
  /**
   * <code>string swift = 5;</code>
   */
  public com.google.protobuf.ByteString
      getSwiftBytes() {
    java.lang.Object ref = swift_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      swift_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOR_ACCOUNT_OF_FIELD_NUMBER = 6;
  private volatile java.lang.Object forAccountOf_;
  /**
   * <code>string for_account_of = 6;</code>
   */
  public java.lang.String getForAccountOf() {
    java.lang.Object ref = forAccountOf_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      forAccountOf_ = s;
      return s;
    }
  }
  /**
   * <code>string for_account_of = 6;</code>
   */
  public com.google.protobuf.ByteString
      getForAccountOfBytes() {
    java.lang.Object ref = forAccountOf_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      forAccountOf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCOUNT_NUMBER_FIELD_NUMBER = 7;
  private volatile java.lang.Object accountNumber_;
  /**
   * <code>string account_number = 7;</code>
   */
  public java.lang.String getAccountNumber() {
    java.lang.Object ref = accountNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accountNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string account_number = 7;</code>
   */
  public com.google.protobuf.ByteString
      getAccountNumberBytes() {
    java.lang.Object ref = accountNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accountNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IN_FAVOUR_OF_FIELD_NUMBER = 8;
  private volatile java.lang.Object inFavourOf_;
  /**
   * <code>string in_favour_of = 8;</code>
   */
  public java.lang.String getInFavourOf() {
    java.lang.Object ref = inFavourOf_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inFavourOf_ = s;
      return s;
    }
  }
  /**
   * <code>string in_favour_of = 8;</code>
   */
  public com.google.protobuf.ByteString
      getInFavourOfBytes() {
    java.lang.Object ref = inFavourOf_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inFavourOf_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IN_FAVOUR_OF_ACCOUNT_NUMBER_FIELD_NUMBER = 9;
  private volatile java.lang.Object inFavourOfAccountNumber_;
  /**
   * <code>string in_favour_of_account_number = 9;</code>
   */
  public java.lang.String getInFavourOfAccountNumber() {
    java.lang.Object ref = inFavourOfAccountNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      inFavourOfAccountNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string in_favour_of_account_number = 9;</code>
   */
  public com.google.protobuf.ByteString
      getInFavourOfAccountNumberBytes() {
    java.lang.Object ref = inFavourOfAccountNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      inFavourOfAccountNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BANK_ID_FIELD_NUMBER = 10;
  private long bankId_;
  /**
   * <code>int64 bank_id = 10;</code>
   */
  public long getBankId() {
    return bankId_;
  }

  public static final int BANK_FIELD_NUMBER = 11;
  private com.personal.models.Bank bank_;
  /**
   * <code>.Bank bank = 11;</code>
   */
  public boolean hasBank() {
    return bank_ != null;
  }
  /**
   * <code>.Bank bank = 11;</code>
   */
  public com.personal.models.Bank getBank() {
    return bank_ == null ? com.personal.models.Bank.getDefaultInstance() : bank_;
  }
  /**
   * <code>.Bank bank = 11;</code>
   */
  public com.personal.models.BankOrBuilder getBankOrBuilder() {
    return getBank();
  }

  public static final int PRODUCTS_FIELD_NUMBER = 12;
  private java.util.List<com.personal.models.Product> products_;
  /**
   * <code>repeated .Product products = 12;</code>
   */
  public java.util.List<com.personal.models.Product> getProductsList() {
    return products_;
  }
  /**
   * <code>repeated .Product products = 12;</code>
   */
  public java.util.List<? extends com.personal.models.ProductOrBuilder> 
      getProductsOrBuilderList() {
    return products_;
  }
  /**
   * <code>repeated .Product products = 12;</code>
   */
  public int getProductsCount() {
    return products_.size();
  }
  /**
   * <code>repeated .Product products = 12;</code>
   */
  public com.personal.models.Product getProducts(int index) {
    return products_.get(index);
  }
  /**
   * <code>repeated .Product products = 12;</code>
   */
  public com.personal.models.ProductOrBuilder getProductsOrBuilder(
      int index) {
    return products_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getBankNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bankName_);
    }
    if (id_ != 0L) {
      output.writeInt64(3, id_);
    }
    if (abaNumber_ != 0L) {
      output.writeInt64(4, abaNumber_);
    }
    if (!getSwiftBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, swift_);
    }
    if (!getForAccountOfBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, forAccountOf_);
    }
    if (!getAccountNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, accountNumber_);
    }
    if (!getInFavourOfBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, inFavourOf_);
    }
    if (!getInFavourOfAccountNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, inFavourOfAccountNumber_);
    }
    if (bankId_ != 0L) {
      output.writeInt64(10, bankId_);
    }
    if (bank_ != null) {
      output.writeMessage(11, getBank());
    }
    for (int i = 0; i < products_.size(); i++) {
      output.writeMessage(12, products_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getBankNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bankName_);
    }
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, id_);
    }
    if (abaNumber_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, abaNumber_);
    }
    if (!getSwiftBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, swift_);
    }
    if (!getForAccountOfBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, forAccountOf_);
    }
    if (!getAccountNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, accountNumber_);
    }
    if (!getInFavourOfBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, inFavourOf_);
    }
    if (!getInFavourOfAccountNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, inFavourOfAccountNumber_);
    }
    if (bankId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, bankId_);
    }
    if (bank_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getBank());
    }
    for (int i = 0; i < products_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, products_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.personal.models.WiringInstruction)) {
      return super.equals(obj);
    }
    com.personal.models.WiringInstruction other = (com.personal.models.WiringInstruction) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getBankName()
        .equals(other.getBankName());
    result = result && (getId()
        == other.getId());
    result = result && (getAbaNumber()
        == other.getAbaNumber());
    result = result && getSwift()
        .equals(other.getSwift());
    result = result && getForAccountOf()
        .equals(other.getForAccountOf());
    result = result && getAccountNumber()
        .equals(other.getAccountNumber());
    result = result && getInFavourOf()
        .equals(other.getInFavourOf());
    result = result && getInFavourOfAccountNumber()
        .equals(other.getInFavourOfAccountNumber());
    result = result && (getBankId()
        == other.getBankId());
    result = result && (hasBank() == other.hasBank());
    if (hasBank()) {
      result = result && getBank()
          .equals(other.getBank());
    }
    result = result && getProductsList()
        .equals(other.getProductsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + BANK_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getBankName().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + ABA_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAbaNumber());
    hash = (37 * hash) + SWIFT_FIELD_NUMBER;
    hash = (53 * hash) + getSwift().hashCode();
    hash = (37 * hash) + FOR_ACCOUNT_OF_FIELD_NUMBER;
    hash = (53 * hash) + getForAccountOf().hashCode();
    hash = (37 * hash) + ACCOUNT_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getAccountNumber().hashCode();
    hash = (37 * hash) + IN_FAVOUR_OF_FIELD_NUMBER;
    hash = (53 * hash) + getInFavourOf().hashCode();
    hash = (37 * hash) + IN_FAVOUR_OF_ACCOUNT_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getInFavourOfAccountNumber().hashCode();
    hash = (37 * hash) + BANK_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBankId());
    if (hasBank()) {
      hash = (37 * hash) + BANK_FIELD_NUMBER;
      hash = (53 * hash) + getBank().hashCode();
    }
    if (getProductsCount() > 0) {
      hash = (37 * hash) + PRODUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getProductsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.personal.models.WiringInstruction parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.personal.models.WiringInstruction parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.personal.models.WiringInstruction parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.personal.models.WiringInstruction parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.personal.models.WiringInstruction parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.personal.models.WiringInstruction parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.personal.models.WiringInstruction parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.personal.models.WiringInstruction parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.personal.models.WiringInstruction parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.personal.models.WiringInstruction parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.personal.models.WiringInstruction parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.personal.models.WiringInstruction parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.personal.models.WiringInstruction prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WiringInstruction}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WiringInstruction)
      com.personal.models.WiringInstructionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.personal.models.GraphQLServiceProto.internal_static_WiringInstruction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.personal.models.GraphQLServiceProto.internal_static_WiringInstruction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.personal.models.WiringInstruction.class, com.personal.models.WiringInstruction.Builder.class);
    }

    // Construct using com.personal.models.WiringInstruction.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getProductsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      bankName_ = "";

      id_ = 0L;

      abaNumber_ = 0L;

      swift_ = "";

      forAccountOf_ = "";

      accountNumber_ = "";

      inFavourOf_ = "";

      inFavourOfAccountNumber_ = "";

      bankId_ = 0L;

      if (bankBuilder_ == null) {
        bank_ = null;
      } else {
        bank_ = null;
        bankBuilder_ = null;
      }
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
      } else {
        productsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.personal.models.GraphQLServiceProto.internal_static_WiringInstruction_descriptor;
    }

    @java.lang.Override
    public com.personal.models.WiringInstruction getDefaultInstanceForType() {
      return com.personal.models.WiringInstruction.getDefaultInstance();
    }

    @java.lang.Override
    public com.personal.models.WiringInstruction build() {
      com.personal.models.WiringInstruction result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.personal.models.WiringInstruction buildPartial() {
      com.personal.models.WiringInstruction result = new com.personal.models.WiringInstruction(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.bankName_ = bankName_;
      result.id_ = id_;
      result.abaNumber_ = abaNumber_;
      result.swift_ = swift_;
      result.forAccountOf_ = forAccountOf_;
      result.accountNumber_ = accountNumber_;
      result.inFavourOf_ = inFavourOf_;
      result.inFavourOfAccountNumber_ = inFavourOfAccountNumber_;
      result.bankId_ = bankId_;
      if (bankBuilder_ == null) {
        result.bank_ = bank_;
      } else {
        result.bank_ = bankBuilder_.build();
      }
      if (productsBuilder_ == null) {
        if (((bitField0_ & 0x00000800) == 0x00000800)) {
          products_ = java.util.Collections.unmodifiableList(products_);
          bitField0_ = (bitField0_ & ~0x00000800);
        }
        result.products_ = products_;
      } else {
        result.products_ = productsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.personal.models.WiringInstruction) {
        return mergeFrom((com.personal.models.WiringInstruction)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.personal.models.WiringInstruction other) {
      if (other == com.personal.models.WiringInstruction.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getBankName().isEmpty()) {
        bankName_ = other.bankName_;
        onChanged();
      }
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getAbaNumber() != 0L) {
        setAbaNumber(other.getAbaNumber());
      }
      if (!other.getSwift().isEmpty()) {
        swift_ = other.swift_;
        onChanged();
      }
      if (!other.getForAccountOf().isEmpty()) {
        forAccountOf_ = other.forAccountOf_;
        onChanged();
      }
      if (!other.getAccountNumber().isEmpty()) {
        accountNumber_ = other.accountNumber_;
        onChanged();
      }
      if (!other.getInFavourOf().isEmpty()) {
        inFavourOf_ = other.inFavourOf_;
        onChanged();
      }
      if (!other.getInFavourOfAccountNumber().isEmpty()) {
        inFavourOfAccountNumber_ = other.inFavourOfAccountNumber_;
        onChanged();
      }
      if (other.getBankId() != 0L) {
        setBankId(other.getBankId());
      }
      if (other.hasBank()) {
        mergeBank(other.getBank());
      }
      if (productsBuilder_ == null) {
        if (!other.products_.isEmpty()) {
          if (products_.isEmpty()) {
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000800);
          } else {
            ensureProductsIsMutable();
            products_.addAll(other.products_);
          }
          onChanged();
        }
      } else {
        if (!other.products_.isEmpty()) {
          if (productsBuilder_.isEmpty()) {
            productsBuilder_.dispose();
            productsBuilder_ = null;
            products_ = other.products_;
            bitField0_ = (bitField0_ & ~0x00000800);
            productsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProductsFieldBuilder() : null;
          } else {
            productsBuilder_.addAllMessages(other.products_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.personal.models.WiringInstruction parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.personal.models.WiringInstruction) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bankName_ = "";
    /**
     * <code>string bank_name = 2;</code>
     */
    public java.lang.String getBankName() {
      java.lang.Object ref = bankName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bankName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bank_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBankNameBytes() {
      java.lang.Object ref = bankName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bankName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bank_name = 2;</code>
     */
    public Builder setBankName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bankName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bank_name = 2;</code>
     */
    public Builder clearBankName() {
      
      bankName_ = getDefaultInstance().getBankName();
      onChanged();
      return this;
    }
    /**
     * <code>string bank_name = 2;</code>
     */
    public Builder setBankNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bankName_ = value;
      onChanged();
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 3;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 3;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 3;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long abaNumber_ ;
    /**
     * <code>int64 aba_number = 4;</code>
     */
    public long getAbaNumber() {
      return abaNumber_;
    }
    /**
     * <code>int64 aba_number = 4;</code>
     */
    public Builder setAbaNumber(long value) {
      
      abaNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 aba_number = 4;</code>
     */
    public Builder clearAbaNumber() {
      
      abaNumber_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object swift_ = "";
    /**
     * <code>string swift = 5;</code>
     */
    public java.lang.String getSwift() {
      java.lang.Object ref = swift_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        swift_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string swift = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSwiftBytes() {
      java.lang.Object ref = swift_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        swift_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string swift = 5;</code>
     */
    public Builder setSwift(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      swift_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string swift = 5;</code>
     */
    public Builder clearSwift() {
      
      swift_ = getDefaultInstance().getSwift();
      onChanged();
      return this;
    }
    /**
     * <code>string swift = 5;</code>
     */
    public Builder setSwiftBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      swift_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object forAccountOf_ = "";
    /**
     * <code>string for_account_of = 6;</code>
     */
    public java.lang.String getForAccountOf() {
      java.lang.Object ref = forAccountOf_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        forAccountOf_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string for_account_of = 6;</code>
     */
    public com.google.protobuf.ByteString
        getForAccountOfBytes() {
      java.lang.Object ref = forAccountOf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        forAccountOf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string for_account_of = 6;</code>
     */
    public Builder setForAccountOf(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      forAccountOf_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string for_account_of = 6;</code>
     */
    public Builder clearForAccountOf() {
      
      forAccountOf_ = getDefaultInstance().getForAccountOf();
      onChanged();
      return this;
    }
    /**
     * <code>string for_account_of = 6;</code>
     */
    public Builder setForAccountOfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      forAccountOf_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accountNumber_ = "";
    /**
     * <code>string account_number = 7;</code>
     */
    public java.lang.String getAccountNumber() {
      java.lang.Object ref = accountNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accountNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string account_number = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAccountNumberBytes() {
      java.lang.Object ref = accountNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accountNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string account_number = 7;</code>
     */
    public Builder setAccountNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accountNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string account_number = 7;</code>
     */
    public Builder clearAccountNumber() {
      
      accountNumber_ = getDefaultInstance().getAccountNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string account_number = 7;</code>
     */
    public Builder setAccountNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accountNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inFavourOf_ = "";
    /**
     * <code>string in_favour_of = 8;</code>
     */
    public java.lang.String getInFavourOf() {
      java.lang.Object ref = inFavourOf_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inFavourOf_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string in_favour_of = 8;</code>
     */
    public com.google.protobuf.ByteString
        getInFavourOfBytes() {
      java.lang.Object ref = inFavourOf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inFavourOf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string in_favour_of = 8;</code>
     */
    public Builder setInFavourOf(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inFavourOf_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string in_favour_of = 8;</code>
     */
    public Builder clearInFavourOf() {
      
      inFavourOf_ = getDefaultInstance().getInFavourOf();
      onChanged();
      return this;
    }
    /**
     * <code>string in_favour_of = 8;</code>
     */
    public Builder setInFavourOfBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inFavourOf_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object inFavourOfAccountNumber_ = "";
    /**
     * <code>string in_favour_of_account_number = 9;</code>
     */
    public java.lang.String getInFavourOfAccountNumber() {
      java.lang.Object ref = inFavourOfAccountNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        inFavourOfAccountNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string in_favour_of_account_number = 9;</code>
     */
    public com.google.protobuf.ByteString
        getInFavourOfAccountNumberBytes() {
      java.lang.Object ref = inFavourOfAccountNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        inFavourOfAccountNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string in_favour_of_account_number = 9;</code>
     */
    public Builder setInFavourOfAccountNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      inFavourOfAccountNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string in_favour_of_account_number = 9;</code>
     */
    public Builder clearInFavourOfAccountNumber() {
      
      inFavourOfAccountNumber_ = getDefaultInstance().getInFavourOfAccountNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string in_favour_of_account_number = 9;</code>
     */
    public Builder setInFavourOfAccountNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      inFavourOfAccountNumber_ = value;
      onChanged();
      return this;
    }

    private long bankId_ ;
    /**
     * <code>int64 bank_id = 10;</code>
     */
    public long getBankId() {
      return bankId_;
    }
    /**
     * <code>int64 bank_id = 10;</code>
     */
    public Builder setBankId(long value) {
      
      bankId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 bank_id = 10;</code>
     */
    public Builder clearBankId() {
      
      bankId_ = 0L;
      onChanged();
      return this;
    }

    private com.personal.models.Bank bank_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.personal.models.Bank, com.personal.models.Bank.Builder, com.personal.models.BankOrBuilder> bankBuilder_;
    /**
     * <code>.Bank bank = 11;</code>
     */
    public boolean hasBank() {
      return bankBuilder_ != null || bank_ != null;
    }
    /**
     * <code>.Bank bank = 11;</code>
     */
    public com.personal.models.Bank getBank() {
      if (bankBuilder_ == null) {
        return bank_ == null ? com.personal.models.Bank.getDefaultInstance() : bank_;
      } else {
        return bankBuilder_.getMessage();
      }
    }
    /**
     * <code>.Bank bank = 11;</code>
     */
    public Builder setBank(com.personal.models.Bank value) {
      if (bankBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bank_ = value;
        onChanged();
      } else {
        bankBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Bank bank = 11;</code>
     */
    public Builder setBank(
        com.personal.models.Bank.Builder builderForValue) {
      if (bankBuilder_ == null) {
        bank_ = builderForValue.build();
        onChanged();
      } else {
        bankBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Bank bank = 11;</code>
     */
    public Builder mergeBank(com.personal.models.Bank value) {
      if (bankBuilder_ == null) {
        if (bank_ != null) {
          bank_ =
            com.personal.models.Bank.newBuilder(bank_).mergeFrom(value).buildPartial();
        } else {
          bank_ = value;
        }
        onChanged();
      } else {
        bankBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Bank bank = 11;</code>
     */
    public Builder clearBank() {
      if (bankBuilder_ == null) {
        bank_ = null;
        onChanged();
      } else {
        bank_ = null;
        bankBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Bank bank = 11;</code>
     */
    public com.personal.models.Bank.Builder getBankBuilder() {
      
      onChanged();
      return getBankFieldBuilder().getBuilder();
    }
    /**
     * <code>.Bank bank = 11;</code>
     */
    public com.personal.models.BankOrBuilder getBankOrBuilder() {
      if (bankBuilder_ != null) {
        return bankBuilder_.getMessageOrBuilder();
      } else {
        return bank_ == null ?
            com.personal.models.Bank.getDefaultInstance() : bank_;
      }
    }
    /**
     * <code>.Bank bank = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.personal.models.Bank, com.personal.models.Bank.Builder, com.personal.models.BankOrBuilder> 
        getBankFieldBuilder() {
      if (bankBuilder_ == null) {
        bankBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.personal.models.Bank, com.personal.models.Bank.Builder, com.personal.models.BankOrBuilder>(
                getBank(),
                getParentForChildren(),
                isClean());
        bank_ = null;
      }
      return bankBuilder_;
    }

    private java.util.List<com.personal.models.Product> products_ =
      java.util.Collections.emptyList();
    private void ensureProductsIsMutable() {
      if (!((bitField0_ & 0x00000800) == 0x00000800)) {
        products_ = new java.util.ArrayList<com.personal.models.Product>(products_);
        bitField0_ |= 0x00000800;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.personal.models.Product, com.personal.models.Product.Builder, com.personal.models.ProductOrBuilder> productsBuilder_;

    /**
     * <code>repeated .Product products = 12;</code>
     */
    public java.util.List<com.personal.models.Product> getProductsList() {
      if (productsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(products_);
      } else {
        return productsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public int getProductsCount() {
      if (productsBuilder_ == null) {
        return products_.size();
      } else {
        return productsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public com.personal.models.Product getProducts(int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);
      } else {
        return productsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder setProducts(
        int index, com.personal.models.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.set(index, value);
        onChanged();
      } else {
        productsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder setProducts(
        int index, com.personal.models.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.set(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder addProducts(com.personal.models.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(value);
        onChanged();
      } else {
        productsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder addProducts(
        int index, com.personal.models.Product value) {
      if (productsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProductsIsMutable();
        products_.add(index, value);
        onChanged();
      } else {
        productsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder addProducts(
        com.personal.models.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder addProducts(
        int index, com.personal.models.Product.Builder builderForValue) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.add(index, builderForValue.build());
        onChanged();
      } else {
        productsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder addAllProducts(
        java.lang.Iterable<? extends com.personal.models.Product> values) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, products_);
        onChanged();
      } else {
        productsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder clearProducts() {
      if (productsBuilder_ == null) {
        products_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000800);
        onChanged();
      } else {
        productsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public Builder removeProducts(int index) {
      if (productsBuilder_ == null) {
        ensureProductsIsMutable();
        products_.remove(index);
        onChanged();
      } else {
        productsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public com.personal.models.Product.Builder getProductsBuilder(
        int index) {
      return getProductsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public com.personal.models.ProductOrBuilder getProductsOrBuilder(
        int index) {
      if (productsBuilder_ == null) {
        return products_.get(index);  } else {
        return productsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public java.util.List<? extends com.personal.models.ProductOrBuilder> 
         getProductsOrBuilderList() {
      if (productsBuilder_ != null) {
        return productsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(products_);
      }
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public com.personal.models.Product.Builder addProductsBuilder() {
      return getProductsFieldBuilder().addBuilder(
          com.personal.models.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public com.personal.models.Product.Builder addProductsBuilder(
        int index) {
      return getProductsFieldBuilder().addBuilder(
          index, com.personal.models.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .Product products = 12;</code>
     */
    public java.util.List<com.personal.models.Product.Builder> 
         getProductsBuilderList() {
      return getProductsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.personal.models.Product, com.personal.models.Product.Builder, com.personal.models.ProductOrBuilder> 
        getProductsFieldBuilder() {
      if (productsBuilder_ == null) {
        productsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.personal.models.Product, com.personal.models.Product.Builder, com.personal.models.ProductOrBuilder>(
                products_,
                ((bitField0_ & 0x00000800) == 0x00000800),
                getParentForChildren(),
                isClean());
        products_ = null;
      }
      return productsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WiringInstruction)
  }

  // @@protoc_insertion_point(class_scope:WiringInstruction)
  private static final com.personal.models.WiringInstruction DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.personal.models.WiringInstruction();
  }

  public static com.personal.models.WiringInstruction getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WiringInstruction>
      PARSER = new com.google.protobuf.AbstractParser<WiringInstruction>() {
    @java.lang.Override
    public WiringInstruction parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WiringInstruction(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WiringInstruction> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WiringInstruction> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.personal.models.WiringInstruction getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

