// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: graphqlService.proto

package com.personal.models;

public interface WiringInstructionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WiringInstruction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string bank_name = 2;</code>
   */
  java.lang.String getBankName();
  /**
   * <code>string bank_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getBankNameBytes();

  /**
   * <code>int64 id = 3;</code>
   */
  long getId();

  /**
   * <code>int64 aba_number = 4;</code>
   */
  long getAbaNumber();

  /**
   * <code>string swift = 5;</code>
   */
  java.lang.String getSwift();
  /**
   * <code>string swift = 5;</code>
   */
  com.google.protobuf.ByteString
      getSwiftBytes();

  /**
   * <code>string for_account_of = 6;</code>
   */
  java.lang.String getForAccountOf();
  /**
   * <code>string for_account_of = 6;</code>
   */
  com.google.protobuf.ByteString
      getForAccountOfBytes();

  /**
   * <code>string account_number = 7;</code>
   */
  java.lang.String getAccountNumber();
  /**
   * <code>string account_number = 7;</code>
   */
  com.google.protobuf.ByteString
      getAccountNumberBytes();

  /**
   * <code>string in_favour_of = 8;</code>
   */
  java.lang.String getInFavourOf();
  /**
   * <code>string in_favour_of = 8;</code>
   */
  com.google.protobuf.ByteString
      getInFavourOfBytes();

  /**
   * <code>string in_favour_of_account_number = 9;</code>
   */
  java.lang.String getInFavourOfAccountNumber();
  /**
   * <code>string in_favour_of_account_number = 9;</code>
   */
  com.google.protobuf.ByteString
      getInFavourOfAccountNumberBytes();

  /**
   * <code>int64 bank_id = 10;</code>
   */
  long getBankId();

  /**
   * <code>.Bank bank = 11;</code>
   */
  boolean hasBank();
  /**
   * <code>.Bank bank = 11;</code>
   */
  com.personal.models.Bank getBank();
  /**
   * <code>.Bank bank = 11;</code>
   */
  com.personal.models.BankOrBuilder getBankOrBuilder();

  /**
   * <code>repeated .Product products = 12;</code>
   */
  java.util.List<com.personal.models.Product> 
      getProductsList();
  /**
   * <code>repeated .Product products = 12;</code>
   */
  com.personal.models.Product getProducts(int index);
  /**
   * <code>repeated .Product products = 12;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .Product products = 12;</code>
   */
  java.util.List<? extends com.personal.models.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .Product products = 12;</code>
   */
  com.personal.models.ProductOrBuilder getProductsOrBuilder(
      int index);
}
